# Generated by Django 5.2 on 2025-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credential_type', models.CharField(choices=[('aws', 'AWS'), ('s3', 'S3'), ('ec2', 'EC2')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AWS Credential',
                'verbose_name_plural': 'AWS Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(default=0)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active_users', models.IntegerField(default=0)),
                ('inactive_users', models.IntegerField(default=0)),
                ('pending_users', models.IntegerField(default=0)),
                ('source_bucket', models.CharField(default='', max_length=255)),
                ('last_s3_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Analytics',
                'verbose_name_plural': 'Employee Analytics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
