# Generated by Django 5.2.5 on 2025-09-08 11:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('crm_data', models.JSONField(blank=True, default=dict)),
                ('s3_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('in_crm', models.BooleanField(default=False)),
                ('in_s3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='dashboard_e_email_b4699f_idx'), models.Index(fields=['is_active'], name='dashboard_e_is_acti_955352_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=25)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('total_paused_duration', models.DurationField(default=datetime.timedelta)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='stopped', max_length=20)),
                ('auto_start', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('screenshot_interval', models.IntegerField(default=10)),
                ('last_screenshot_time', models.DateTimeField(blank=True, null=True)),
                ('total_screenshots', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='dashboard.employee')),
            ],
            options={
                'verbose_name': 'Timer Session',
                'verbose_name_plural': 'Timer Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_elapsed_time', models.DurationField()),
                ('uploaded_to_s3', models.BooleanField(default=False)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='dashboard.employee')),
                ('timer_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='dashboard.timersession')),
            ],
            options={
                'verbose_name': 'Screenshot Log',
                'verbose_name_plural': 'Screenshot Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['employee', 'status'], name='dashboard_t_employe_284144_idx'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['start_time'], name='dashboard_t_start_t_1b113e_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshotlog',
            index=models.Index(fields=['timer_session', 'timestamp'], name='dashboard_s_timer_s_0a0653_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshotlog',
            index=models.Index(fields=['employee', 'timestamp'], name='dashboard_s_employe_64f431_idx'),
        ),
    ]
