# Generated by Django 5.2.5 on 2025-09-08 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usertimer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNumericValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, help_text='Numeric value for the user')),
                ('description', models.CharField(blank=True, help_text='Optional description of what this value represents', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_value', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Numeric Value',
                'verbose_name_plural': 'User Numeric Values',
                'ordering': ['-value'],
            },
        ),
    ]
