# Generated by Django 5.2.5 on 2025-09-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usernumericvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1E90FF', help_text='HEX or RGB format (e.g., #1E90FF or rgb(30,144,255))', max_length=50)),
                ('secondary_color', models.CharField(default='#32CD32', help_text='HEX or RGB format', max_length=50)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='HEX or RGB format', max_length=50)),
                ('button_color', models.CharField(default='#007BFF', help_text='HEX or RGB format', max_length=50)),
                ('text_color', models.CharField(default='#333333', help_text='HEX or RGB format', max_length=50)),
                ('heading_font_size', models.CharField(default='24px', help_text="Font size in px or rem (e.g., '24px', '1.5rem')", max_length=20)),
                ('body_font_size', models.CharField(default='16px', help_text='Font size in px or rem', max_length=20)),
                ('font_family', models.CharField(default='Arial', help_text="Font family name (e.g., 'Roboto', 'Arial')", max_length=100)),
                ('border_radius', models.CharField(blank=True, default='5px', help_text="Border radius (e.g., '5px')", max_length=20)),
                ('theme_name', models.CharField(blank=True, help_text='Optional theme name', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description of the styling', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this styling is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='styling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Styling',
                'verbose_name_plural': 'User Stylings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
