# Generated by Django 5.2.5 on 2025-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userstyling'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(default='Default Theme', help_text='Name of the theme', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the styling theme', max_length=200)),
                ('primary_color', models.CharField(default='#1E90FF', help_text='HEX or RGB format (e.g., #1E90FF or rgb(30,144,255))', max_length=50)),
                ('secondary_color', models.CharField(default='#32CD32', help_text='HEX or RGB format', max_length=50)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='HEX or RGB format', max_length=50)),
                ('button_color', models.CharField(default='#007BFF', help_text='HEX or RGB format', max_length=50)),
                ('text_color', models.CharField(default='#333333', help_text='HEX or RGB format', max_length=50)),
                ('heading_font_size', models.CharField(default='24px', help_text="Font size in px or rem (e.g., '24px', '1.5rem')", max_length=20)),
                ('body_font_size', models.CharField(default='16px', help_text='Font size in px or rem', max_length=20)),
                ('font_family', models.CharField(default='Arial', help_text="Font family name (e.g., 'Roboto', 'Arial')", max_length=100)),
                ('border_radius', models.CharField(blank=True, default='5px', help_text="Border radius (e.g., '5px')", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this styling is currently active for the application')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default theme')),
                ('created_by', models.CharField(blank=True, help_text='Who created this theme', max_length=100)),
                ('version', models.CharField(default='1.0', help_text='Theme version', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Styling',
                'verbose_name_plural': 'App Stylings',
                'ordering': ['-is_active', '-is_default', '-updated_at'],
            },
        ),
    ]
