# Generated by Django 5.2.5 on 2025-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_appstyling'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(help_text='Unique name for this credential set', max_length=200, unique=True)),
                ('credential_type', models.CharField(choices=[('aws', 'AWS Credentials'), ('database', 'Database Credentials'), ('openai', 'OpenAI API Key'), ('auth', 'Auth Token'), ('general', 'General Configuration')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this credential configuration')),
                ('aws_access_key_id', models.CharField(blank=True, help_text='AWS Access Key ID', max_length=500)),
                ('aws_secret_access_key', models.CharField(blank=True, help_text='AWS Secret Access Key', max_length=500)),
                ('aws_region', models.CharField(blank=True, default='us-east-1', help_text='AWS Region', max_length=50)),
                ('aws_bucket_name', models.CharField(blank=True, help_text='S3 Bucket Name', max_length=200)),
                ('db_host', models.CharField(blank=True, help_text='Database Host', max_length=200)),
                ('db_port', models.CharField(blank=True, default='5432', help_text='Database Port', max_length=10)),
                ('db_name', models.CharField(blank=True, help_text='Database Name', max_length=200)),
                ('db_username', models.CharField(blank=True, help_text='Database Username', max_length=200)),
                ('db_password', models.CharField(blank=True, help_text='Database Password', max_length=500)),
                ('db_type', models.CharField(blank=True, default='postgresql', help_text='Database Type (postgresql, mysql, etc.)', max_length=50)),
                ('openai_api_key', models.CharField(blank=True, help_text='OpenAI API Key', max_length=500)),
                ('openai_model', models.CharField(blank=True, default='gpt-3.5-turbo', help_text='OpenAI Model', max_length=100)),
                ('openai_organization', models.CharField(blank=True, help_text='OpenAI Organization ID', max_length=200)),
                ('auth_token', models.CharField(blank=True, help_text='Authentication Token', max_length=500)),
                ('auth_refresh_token', models.CharField(blank=True, help_text='Refresh Token', max_length=500)),
                ('auth_token_expires_at', models.DateTimeField(blank=True, help_text='Token Expiration Time', null=True)),
                ('api_base_url', models.URLField(blank=True, help_text='Base API URL')),
                ('api_timeout', models.IntegerField(default=30, help_text='API Timeout in seconds')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug mode')),
                ('is_active', models.BooleanField(default=True, help_text='Is this credential set currently active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default credential set?')),
                ('environment', models.CharField(default='development', help_text='Environment (development, staging, production)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Who created this configuration', max_length=200)),
            ],
            options={
                'verbose_name': 'System Credential',
                'verbose_name_plural': 'System Credentials',
                'ordering': ['-is_active', '-is_default', '-updated_at'],
            },
        ),
    ]
