# Generated by Django 5.2 on 2025-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_systemcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstyling',
            name='drawer_background_color',
            field=models.CharField(default='#f8f9fa', help_text='Drawer/sidebar background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='drawer_text_color',
            field=models.CharField(default='#212529', help_text='Drawer/sidebar text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='icon_color',
            field=models.CharField(default='#6c757d', help_text='Default icon color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_button_bg_color',
            field=models.CharField(default='#007bff', help_text='Primary button background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_button_text_color',
            field=models.CharField(default='#ffffff', help_text='Primary button text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='secondary_button_bg_color',
            field=models.CharField(default='#6c757d', help_text='Secondary button background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='secondary_button_text_color',
            field=models.CharField(default='#ffffff', help_text='Secondary button text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='submit_button_bg_color',
            field=models.CharField(default='#28a745', help_text='Submit button background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='submit_button_text_color',
            field=models.CharField(default='#ffffff', help_text='Submit button text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='top_color',
            field=models.CharField(default='#007bff', help_text='Top navigation/header color', max_length=50),
        ),
    ]
