# Generated by Django 5.2 on 2025-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_extended_styling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstyling',
            name='background_dark',
            field=models.CharField(default='#343a40', help_text='Dark background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='background_light',
            field=models.CharField(default='#f8f9fa', help_text='Light background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='black',
            field=models.CharField(default='#000000', help_text='Black color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='border_color',
            field=models.CharField(default='#dee2e6', help_text='Border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='button_dark',
            field=models.CharField(default='#004085', help_text='Dark button variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='button_hover',
            field=models.CharField(default='#0056b3', help_text='Button hover state', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='button_light',
            field=models.CharField(default='#66b3ff', help_text='Light button variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='Button text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='danger_color',
            field=models.CharField(default='#dc3545', help_text='Danger state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='danger_dark',
            field=models.CharField(default='#c82333', help_text='Danger dark variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='drawer_border',
            field=models.CharField(default='rgba(0, 96, 57, 0.1)', help_text='Drawer border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='drawer_overlay',
            field=models.CharField(default='rgba(0, 0, 0, 0.6)', help_text='Drawer overlay color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='drawer_shadow',
            field=models.CharField(default='rgba(0, 96, 57, 0.15)', help_text='Drawer shadow color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='footer_color',
            field=models.CharField(default='#003366', help_text='Footer color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_100',
            field=models.CharField(default='#f8f9fa', help_text='Gray 100', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_200',
            field=models.CharField(default='#e9ecef', help_text='Gray 200', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_300',
            field=models.CharField(default='#dee2e6', help_text='Gray 300', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_400',
            field=models.CharField(default='#ced4da', help_text='Gray 400', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_500',
            field=models.CharField(default='#adb5bd', help_text='Gray 500', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_600',
            field=models.CharField(default='#6c757d', help_text='Gray 600', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_700',
            field=models.CharField(default='#495057', help_text='Gray 700', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_800',
            field=models.CharField(default='#343a40', help_text='Gray 800', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='gray_900',
            field=models.CharField(default='#212529', help_text='Gray 900', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='header_color',
            field=models.CharField(default='#003366', help_text='Header color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='info_color',
            field=models.CharField(default='#17a2b8', help_text='Info state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_background',
            field=models.CharField(default='#ffffff', help_text='Input background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_border',
            field=models.CharField(default='#ced4da', help_text='Input border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_focus',
            field=models.CharField(default='#80bdff', help_text='Input focus color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_text',
            field=models.CharField(default='#495057', help_text='Input text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_background',
            field=models.CharField(default='#ffffff', help_text='Modal background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_border',
            field=models.CharField(default='#dee2e6', help_text='Modal border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_overlay',
            field=models.CharField(default='rgba(0, 0, 0, 0.6)', help_text='Modal overlay color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='nav_active',
            field=models.CharField(default='#0056b3', help_text='Navigation active color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='nav_background',
            field=models.CharField(default='#003366', help_text='Navigation background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='nav_hover',
            field=models.CharField(default='rgba(255, 255, 255, 0.1)', help_text='Navigation hover color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='nav_text',
            field=models.CharField(default='#ffffff', help_text='Navigation text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_active',
            field=models.CharField(default='#004426', help_text='Primary active state', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_dark',
            field=models.CharField(default='#004d2e', help_text='Primary dark variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_darker',
            field=models.CharField(default='#003d24', help_text='Primary darker variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_hover',
            field=models.CharField(default='#005530', help_text='Primary hover state', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='primary_light',
            field=models.CharField(default='#00804d', help_text='Primary light variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='secondary_dark',
            field=models.CharField(default='#5a6268', help_text='Secondary dark variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='secondary_light',
            field=models.CharField(default='#adb5bd', help_text='Secondary light variant', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='state_break',
            field=models.CharField(default='#ffc107', help_text='Timer break state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='state_idle',
            field=models.CharField(default='#6c757d', help_text='Timer idle state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='state_meeting',
            field=models.CharField(default='#17a2b8', help_text='Timer meeting state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='state_work',
            field=models.CharField(default='#006039', help_text='Timer work state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='success_color',
            field=models.CharField(default='#28a745', help_text='Success state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='text_dark',
            field=models.CharField(default='#212529', help_text='Dark text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='text_light',
            field=models.CharField(default='#6c757d', help_text='Light text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='warning_color',
            field=models.CharField(default='#ffc107', help_text='Warning state color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='white',
            field=models.CharField(default='#ffffff', help_text='White color', max_length=50),
        ),
    ]
