# Generated by Django 5.2 on 2025-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_complete_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstyling',
            name='checkbox_bg',
            field=models.CharField(default='#FFFFFF', help_text='Checkbox background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='checkbox_checked',
            field=models.CharField(default='#1E88E5', help_text='Checkbox checked color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_invalid_border',
            field=models.CharField(default='#F44336', help_text='Invalid input border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_placeholder',
            field=models.CharField(default='#999999', help_text='Input placeholder text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='input_valid_border',
            field=models.CharField(default='#4CAF50', help_text='Valid input border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='language_border',
            field=models.CharField(default='#E0E0E0', help_text='Language selector border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='language_dropdown_bg',
            field=models.CharField(default='#FFFFFF', help_text='Language dropdown background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='language_option_hover',
            field=models.CharField(default='#F5F5F5', help_text='Language option hover color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_background',
            field=models.CharField(default='#E8EDF2', help_text='Login page background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_button_bg',
            field=models.CharField(default='#FF7043', help_text='Login button background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_button_hover',
            field=models.CharField(default='#FF5722', help_text='Login button hover color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_button_text',
            field=models.CharField(default='#FFFFFF', help_text='Login button text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_card_bg',
            field=models.CharField(default='#FFFFFF', help_text='Login card background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_error_color',
            field=models.CharField(default='#F44336', help_text='Login error color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_header_bg',
            field=models.CharField(default='#1E88E5', help_text='Login header background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_input_bg',
            field=models.CharField(default='#FFFFFF', help_text='Login input background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_input_border',
            field=models.CharField(default='#E0E0E0', help_text='Login input border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_input_focus',
            field=models.CharField(default='#1E88E5', help_text='Login input focus color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_link_color',
            field=models.CharField(default='#1E88E5', help_text='Login link color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_success_color',
            field=models.CharField(default='#4CAF50', help_text='Login success color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_text_primary',
            field=models.CharField(default='#333333', help_text='Login primary text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='login_text_secondary',
            field=models.CharField(default='#666666', help_text='Login secondary text color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_border_color',
            field=models.CharField(default='#E0E0E0', help_text='Modal border color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_close_bg',
            field=models.CharField(default='#FF5722', help_text='Modal close button background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_close_hover',
            field=models.CharField(default='#FF3D00', help_text='Modal close button hover color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_content_bg',
            field=models.CharField(default='#FFFFFF', help_text='Modal content background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_header_bg',
            field=models.CharField(default='#F5F5F5', help_text='Modal header background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_overlay_bg',
            field=models.CharField(default='rgba(0, 0, 0, 0.6)', help_text='Modal overlay background color', max_length=50),
        ),
        migrations.AddField(
            model_name='appstyling',
            name='modal_shadow',
            field=models.CharField(default='rgba(0, 0, 0, 0.25)', help_text='Modal shadow color', max_length=50),
        ),
    ]
