# Generated by Django 5.2 on 2025-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_login_modal_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscredential',
            name='region',
            field=models.CharField(default='eu-north-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemcredentials',
            name='aws_region',
            field=models.CharField(blank=True, default='eu-north-1', help_text='AWS Region', max_length=50),
        ),
    ]
