# Generated by Django 4.2.7 on 2025-09-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_awscredential_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timer_id', models.AutoField(primary_key=True, serialize=False)),
                ('timer_start', models.DateTimeField(blank=True, help_text='Timer start timestamp - DATETIME NULL', null=True)),
                ('timer_end', models.DateTimeField(blank=True, help_text='Timer end timestamp - DATETIME NULL', null=True)),
                ('total_time_spent', models.FloatField(default=0.0, help_text='Total time spent in seconds - FLOAT DEFAULT 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Foreign key to registered user (auth_user table)', on_delete=django.db.models.deletion.CASCADE, related_name='user_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timer',
                'verbose_name_plural': 'Timers',
                'db_table': 'timer',
                'ordering': ['-timer_id'],
                'indexes': [models.Index(fields=['user', 'timer_start'], name='timer_user_id_b2c489_idx'), models.Index(fields=['timer_start', 'timer_end'], name='timer_timer_s_48d7cb_idx')],
            },
        ),
    ]
