# Generated by Django 4.2.7 on 2025-09-18 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_create_timer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='user',
            field=models.ForeignKey(help_text='Foreign key to registered user (auth_user table)', on_delete=django.db.models.deletion.CASCADE, related_name='timer_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
