# Generated by Django 4.2.7 on 2025-09-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_create_timer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
