# Generated by Django 5.2.4 on 2025-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_timer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='dashboard_e_email_b4699f_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='dashboard_e_is_acti_955352_idx',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_sync',
            new_name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='in_crm',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='in_s3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='s3_data',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='crm_id',
            field=models.CharField(blank=True, help_text='ID from CRM system', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='data_source',
            field=models.CharField(choices=[('crm', 'CRM System'), ('local', 'Local Database'), ('s3', 'S3 Bucket'), ('combined', 'Combined Sources')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='crm_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw CRM data'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
