#!/usr/bin/env python3
"""
Simple API Test - Show All Available Endpoints
"""

print("🔗 ALL PROJECT STATUS API ENDPOINTS")
print("=" * 60)

print("\n📋 COMPREHENSIVE API (NEW - Single endpoint with multiple formats):")
print("-" * 60)
print("GET /api/projects/status/?format=simple")
print("  → Just numbers: {not_started: 2, in_progress: 34, ...}")
print()
print("GET /api/projects/status/?format=detailed")
print("  → Numbers + percentages + metadata")
print()
print("GET /api/projects/status/?format=breakdown")
print("  → Numbers + sample projects by status")
print()  
print("GET /api/projects/status/?format=all")
print("  → Complete comprehensive response")
print()
print("GET /api/projects/status/?format=breakdown&include_projects=true")
print("  → All projects grouped by status")

print("\n🗄️ STATIC CRM APIs (Original):")
print("-" * 60)
print("GET /api/projects/simple-counts/")
print("GET /api/projects/static-status/")
print("GET /api/projects/status-breakdown/")

print("\n🤖 AI-POWERED APIs:")
print("-" * 60)
print("GET /api/projects/ai-categorization/")
print("GET /api/projects/status-summary/")

print("\n📊 ACCURATE CRM APIs:")
print("-" * 60)
print("GET /api/projects/accurate-status/")
print("GET /api/projects/dashboard-counts/")

print("\n📝 BASIC PROJECT APIs:")
print("-" * 60)
print("GET /api/projects/all/")
print("GET /api/projects/management/")

print("\n🎯 RECOMMENDED FOR YOUR DASHBOARD:")
print("-" * 60)
print("🔥 USE THIS: GET /api/projects/status/?format=simple")
print()
print("📱 Frontend JavaScript:")
print("fetch('/api/projects/status/?format=simple')")
print("  .then(response => response.json())")
print("  .then(data => {")
print("    // data.not_started = 2")
print("    // data.in_progress = 34")
print("    // data.onhold = 4")  
print("    // data.cancel = 6")
print("    // data.finished = 243")
print("  });")

print("\n✅ Exact Dashboard Numbers:")
print("🔵 Not Started: 2")
print("🟠 In Progress: 34")
print("🟡 Hold: 4")
print("🔴 Cancelled: 6")
print("🟢 Finished: 243")
print("📋 Total: 289")

print("\n🚀 All endpoints return STATIC data from CRM database!")
print("💡 Use format parameter to get different response structures!")
