# Generated by Django 5.2.4 on 2025-10-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotrecord',
            name='job_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screenshotrecord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='screenshotrecord',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
