# Generated by Django 4.2.11 on 2025-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_screenshotrecord_job_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshotrecord',
            name='screenshot_time',
        ),
        migrations.AddField(
            model_name='screenshotrecord',
            name='screenshot_interval',
            field=models.PositiveIntegerField(default=4, help_text='Enter screenshot interval in minutes.'),
            preserve_default=False,
        ),
    ]
