# Generated by Django 5.2 on 2025-07-18 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON Object')], default='string', max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Setting',
                'verbose_name_plural': 'Application Settings',
                'db_table': 'application_settings',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name (e.g., admin_uploaded, http_database)', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('upload', 'Upload Configuration'), ('database', 'Database Configuration'), ('aws', 'AWS Configuration')], help_text='Type of configuration', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration', null=True)),
                ('config_data', models.JSONField(default=dict, help_text='Configuration parameters as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Setting',
                'verbose_name_plural': 'Configuration Settings',
                'db_table': 'configuration_settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('jsonlog', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credential_type', models.CharField(choices=[('openai', 'OpenAI API Key'), ('aws', 'AWS Credentials'), ('database', 'Database Configuration'), ('smtp', 'SMTP Email Configuration'), ('oauth', 'OAuth Configuration'), ('api_key', 'Generic API Key'), ('storage', 'Storage Service'), ('payment', 'Payment Gateway')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.TextField(blank=True)),
                ('secret_key', models.TextField(blank=True)),
                ('access_key', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255)),
                ('additional_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Credential',
                'verbose_name_plural': 'System Credentials',
                'db_table': 'system_credentials',
            },
        ),
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(default='default', max_length=100)),
                ('is_global', models.BooleanField(default=False, help_text='Apply to all users globally')),
                ('font_family', models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('Times New Roman, serif', 'Times New Roman'), ('Georgia, serif', 'Georgia'), ('Verdana, sans-serif', 'Verdana'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Montserrat, sans-serif', 'Montserrat'), ('Source Sans Pro, sans-serif', 'Source Sans Pro')], default='Arial, sans-serif', max_length=100)),
                ('font_size', models.CharField(choices=[('12px', 'Extra Small (12px)'), ('14px', 'Small (14px)'), ('16px', 'Medium (16px)'), ('18px', 'Large (18px)'), ('20px', 'Extra Large (20px)'), ('24px', 'XXL (24px)')], default='16px', max_length=10)),
                ('primary_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('background_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('text_color', models.CharField(default='#333333', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UI Setting',
                'verbose_name_plural': 'UI Settings',
                'db_table': 'ui_settings',
            },
        ),
    ]
