# Generated by Django 5.2 on 2025-09-13 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, help_text="User's organization name", max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text="User's country", max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('bio', models.TextField(blank=True, help_text="User's biography", max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, help_text="User's job title", max_length=100, null=True)),
                ('industry', models.CharField(blank=True, help_text="User's industry", max_length=100, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive')], help_text="User's experience level", max_length=20, null=True)),
                ('profile_completed', models.BooleanField(default=False, help_text='Whether user has completed their profile')),
                ('email_notifications', models.BooleanField(default=True, help_text="User's email notification preference")),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', help_text="User's privacy level", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_userprofile',
            },
        ),
    ]
