# Generated by Django 4.2.7 on 2025-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numeric_value',
            field=models.IntegerField(default=0, help_text='Numeric value parameter for user'),
        ),
    ]
