# Generated by Django 5.2 on 2025-08-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_file', models.CharField(help_text='S3 inventory file path', max_length=500)),
                ('total_files_processed', models.IntegerField(default=0)),
                ('total_employees_updated', models.IntegerField(default=0)),
                ('processing_duration', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('summary_data', models.JSONField(blank=True, default=dict, help_text='Summary statistics from processing')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyScreenshotCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which the count is recorded')),
                ('total_screenshots', models.IntegerField(default=0, help_text='Total screenshots for this employee on this date')),
                ('s3_inventory_processed_at', models.DateTimeField(blank=True, help_text='When S3 inventory was last processed', null=True)),
                ('s3_inventory_file', models.CharField(blank=True, help_text='S3 inventory file used for this count', max_length=500)),
                ('task_folder_breakdown', models.JSONField(blank=True, default=dict, help_text="Breakdown of screenshots per task folder: {'folder_name': count}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_screenshot_counts', to='dashboard.staff')),
            ],
            options={
                'ordering': ['-date', 'staff__firstname'],
                'indexes': [models.Index(fields=['date'], name='dashboard_d_date_93d946_idx'), models.Index(fields=['staff', 'date'], name='dashboard_d_staff_i_89541e_idx'), models.Index(fields=['-date'], name='dashboard_d_date_cf7b8b_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
